name: Remove preview PR
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.repository_owner == 'saundefined'
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ./home/thephpfoundation/scripts/pr_closed.sh web-php ${{ github.event.number }}
