name: Remove preview PR
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.repository_owner == 'php'
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -rf "/home/thephpfoundation/preview/web-php-pr-${{ github.event.number }}/"
