name: Remove preview PR
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.repository_owner == 'saundefined'
    steps:
      - uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: bash /home/thephpfoundation/scripts/pr_closed.sh web-php ${{ github.event.number }}
          host: ${{ secrets.PREVIEW_REMOTE_HOST }}
          username: ${{ secrets.PREVIEW_REMOTE_USER }}
          privateKey: ${{ secrets.PREVIEW_SSH_KEY }}
