name: Preview PR
on:
  pull_request_target:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.repository_owner == 'saundefined'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: "/var/www/subdomains/pr-${{ github.event.number }}/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT

